---
- name: Kibana
  service:
    name: kibana
    enabled: yes
    state: started

- name: Elasticsearch
  service:
    name: elasticsearch
    enabled: yes
    state: started

- name: Nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Auditd
  service:
    name: auditd
    enabled: yes
    state: started