---
- name: Install Nginx Server
  yum: name=nginx state=latest
 
- name: Replace Nginx Sercer config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: 
  - Start Nginx Server
  tags:
  - nginx_conf
  