# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "websrv" do |websrv|
     websrv.vm.box = "centos/7"
     websrv.vm.network "private_network", ip: "192.168.50.5"
     websrv.vm.hostname = "websrv"
     websrv.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "websrv"]
        vb.memory = "512"
     end
     websrv.vm.provision "shell", inline: <<-SHELL
     yum install -y epel-release
	 yum install -y ansible
	 yum install -y pam_script
     SHELL
     websrv.vm.provision "shell", path: "user.sh"
     websrv.vm.provision "ansible_local" do |ansible|
     ansible.playbook = "playbook.yml"
	 end
    end
end