---
- name: Start and enable firewalld
  service: name=firewalld state=started enabled=yes

- name: Open firewall for external access to MySQL
  firewalld: service=mysql permanent=true immediate=true state=enabled

- name: Open Galera ports on firewall
  firewalld: port={{ item }} permanent=true immediate=true state=enabled
  with_items:
    - 3306/tcp
    - 4444/tcp
    - 4567/tcp
    - 4568/tcp
    - 873/tcp
    - 9200/tcp
    - 514/tcp
    - 514/udp

- name: Open firewall for external access to HTTP
  firewalld: service=http permanent=true immediate=true state=enabled

- name: Add rich rule for keepalived vrrp
  firewalld:
    rich_rule: 'rule protocol value="vrrp" accept'
    permanent: true
    immediate: true
    state: enabled

- name:
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name:
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: Reboot firewall
  systemd:
    state: started
    name: firewalld
