---
- name: Install HAProxy
  yum: name=haproxy

- name: Create OCF directory
  file: path=/usr/lib/ocf/resource.d/heartbeat state=directory mode=0755

- name: Install HAProxy OCF file
  copy: src=haproxy dest=/usr/lib/ocf/resource.d/heartbeat/haproxy owner=root group=root mode=0755

- name: Install HAProxy config file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Enable haproxy to be started at boot
  service: name=haproxy enabled=yes state=started