#!/bin/bash

sysctl net.ipv4.conf.all.forwarding=1
yum install iptables iptables-services -y
systemctl start iptables
#iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
#echo -e '192.168.0.0/28 via 192.168.255.2' > /etc/sysconfig/network-scripts/route-eth1
ip r add 192.168.0.0/28 via 192.168.255.2
ip r add 192.168.254.0/30 via 192.168.255.2
sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd
cat >>/etc/sysconfig/iptables.new<<EOF
# Generated by iptables-save v1.4.7 on Sun Jun  9 18:53:05 2019
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [33:2936]
:SSH-INPUT - [0:0]
:SSH-INPUTTWO - [0:0]
:TRAFFIC - [0:0]
-A INPUT -j TRAFFIC
-A SSH-INPUT -m recent --set --name SSH1 --rsource -j DROP
-A SSH-INPUTTWO -m recent --set --name SSH2 --rsource -j DROP
-A TRAFFIC -p icmp -m icmp --icmp-type any -j ACCEPT
-A TRAFFIC -m state --state RELATED,ESTABLISHED -j ACCEPT
-A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 22 -m recent --rcheck --seconds 30 --name SSH2 --rsource -j ACCEPT
-A TRAFFIC -p tcp -m state --state NEW -m tcp -m recent --remove --name SSH2 --rsource -j DROP
-A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 9991 -m recent --rcheck --name SSH1 --rsource -j SSH-INPUTTWO
-A TRAFFIC -p tcp -m state --state NEW -m tcp -m recent --remove --name SSH1 --rsource -j DROP
-A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 7777 -m recent --rcheck --name SSH0 --rsource -j SSH-INPUT
-A TRAFFIC -p tcp -m state --state NEW -m tcp -m recent --remove --name SSH0 --rsource -j DROP
-A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 8881 -m recent --set --name SSH0 --rsource -j DROP
-A TRAFFIC -j DROP
COMMIT
# Completed on Sun Jun  9 18:53:05 2019
# Generated by iptables-save v1.4.7 on Sun Jun  9 18:53:05 2019
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
COMMIT
# Completed on Sun Jun  9 18:53:05 2019
EOF
iptables-restore < /etc/sysconfig/iptables.new
#systemctl restart iptables
#service iptables restart