---
# tasks file for php

- name: Install php extensions
  yum:
    name: 
    - php
    - php-mysql
    - php-gd
    - php-mcrypt
    - php-fpm
    state: present

- name: Setup php-fpm
  replace: dest=/etc/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart nginx

- name: Start php-fpm
  systemd:  
    name: php-fpm
    state: restarted
    enabled: yes