# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible_local" do |ansible|
#    ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "r1" do |r1|
    r1.vm.network "private_network", ip: "192.168.50.10", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "network"
    r1.vm.network "private_network", ip: "192.168.60.10", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "network"
    r1.vm.hostname = "r1"
  end

  config.vm.define "r2" do |r2|
    r2.vm.network "private_network", ip: "192.168.60.11", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "network"
    r2.vm.network "private_network", ip: "192.168.70.10", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "network"
    r2.vm.hostname = "r2"
  end

  config.vm.define "r3" do |r3|
    r3.vm.network "private_network", ip: "192.168.70.11", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "network"
    r3.vm.network "private_network", ip: "192.168.50.11", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "network"
    r3.vm.hostname = "r3"
  end
  
end