# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "freeipa" do |freeipa|
     freeipa.vm.box = "centos/7"
     freeipa.vm.network "private_network", ip: "192.168.50.15"
     freeipa.vm.hostname = "freeipa"
     freeipa.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "freeipa"]
        vb.memory = "2048"
     end
     freeipa.vm.provision "shell", inline: <<-SHELL
     yum install -y epel-release
	 yum install -y update
	 yum install -y ansible bind-utils vim
	 echo "192.168.50.15  ipa.kvaidoweber.com" | sudo tee -a /etc/hosts
	 hostnamectl set-hostname ipa.kvaidoweber.com
	 yum install -y ipa-server ipa-server-dns bindipa-server bind-dyndb-ldap
	 SHELL
#     freeipa.vm.provision "shell", path: "script.sh"
#     freeipa.vm.provision "ansible_local" do |ansible|
#     ansible.playbook = "playbook.yml"
#	 end
    end
end