# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "freeipa" do |freeipa|
     freeipa.vm.box = "centos/7"
     freeipa.vm.network "private_network", ip: "192.168.50.15"
     freeipa.vm.hostname = "freeipa"
     freeipa.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "freeipa"]
        vb.memory = "2048"
     end
     freeipa.vm.provision "shell", inline: <<-SHELL
     yum install -y epel-release
	 yum install -y update
	 yum install -y ansible vim net-tools
	 echo "192.168.50.15  ipa.kvaido.com  kvaido.com" | sudo tee -a /etc/hosts
	 echo "192.168.50.20  client.kvaido.com  kvaido.com" | sudo tee -a /etc/hosts
#	 hostnamectl set-hostname ipa.kvaido.com
#	 yum install -y ipa-server ipa-server-dns bindipa-server bind-dyndb-ldap bind-utils
	 SHELL
#     freeipa.vm.provision "shell", path: "script.sh"
     freeipa.vm.provision "ansible_local" do |ansible|
     ansible.playbook = "ipasrv.yml"
	 end
    end
  
  config.vm.define "client" do |client|
     client.vm.box = "centos/7"
     client.vm.network "private_network", ip: "192.168.50.20"
     client.vm.hostname = "client"
     client.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "client"]
        vb.memory = "512"
     end
     client.vm.provision "shell", inline: <<-SHELL
     yum install -y epel-release
	 yum install -y update
	 yum install -y ansible vim net-tools
	 echo "192.168.50.15  ipa.kvaido.com  kvaido.com" | sudo tee -a /etc/hosts
	 echo "192.168.50.20  client.kvaido.com  kvaido.com" | sudo tee -a /etc/hosts
	 SHELL
     client.vm.provision "ansible_local" do |ansible|
     ansible.playbook = "ipacli.yml"
	 end

    end
end