# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "freeipa" do |freeipa|
     freeipa.vm.box = "centos/7"
     freeipa.vm.network "private_network", ip: "192.168.50.15"
     freeipa.vm.hostname = "freeipa"
     freeipa.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "freeipa"]
        vb.memory = "512"
     end
     freeipa.vm.provision "shell", inline: <<-SHELL
     yum install -y epel-release
	 yum install -y ansible
     SHELL
#     freeipa.vm.provision "shell", path: "script.sh"
#     freeipa.vm.provision "ansible_local" do |ansible|
#     ansible.playbook = "playbook.yml"
#	 end
    end
end