
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define :nfs do | nfs |
    nfs.vm.hostname = "nfs-srv"
    nfs.vm.network :private_network, ip: "192.168.5.10"
    nfs.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
	yum install -y update
	yum install -y vim net-tools mc
    sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
	setenforce 0
	yum install -y nfs-utils nfs-utils-lib
	systemctl enable nfs-server.service
	systemctl start nfs-server.service
	systemctl enable rpcbind.service
	systemctl start rpcbind.service
	systemctl enable firewalld.service
	systemctl start firewalld.service
    firewall-cmd --permanent --zone=public --add-service=nfs
    firewall-cmd --permanent --zone=public --add-service=mountd
    firewall-cmd --permanent --zone=public --add-service=rpc-bind
    firewall-cmd --reload
    mkdir -p /opt/otus
	chmod -R 777 /opt/otus
    chown nfsnobody:nfsnobody /opt/otus
    echo "/opt/otus 192.168.5.0/24(rw,sync,all_squash,no_subtree_check)" >> /etc/exports
    exportfs -r
	SHELL
  end
  
  config.vm.define :client do | client |
    client.vm.hostname = "nfs-client"
    client.vm.network :private_network, ip: "192.168.5.20"
    client.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
	yum install -y update
	yum install -y vim net-tools mc
    sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
	setenforce 0
	yum install -y nfs-utils
	systemctl enable rpcbind.service
	systemctl start rpcbind.service
    mkdir -p /tmp/otus
    echo "192.168.5.10:/opt/otus /tmp/otus nfs rw,sync,hard,intr 0 0" >> /etc/fstab
    mount -a
	SHELL
  end

end
