---
- name: Download WordPress
  get_url: 
    url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz 
    dest: /tmp/wordpress-{{ wp_version }}.tar.gz 
    checksum: "sha1:{{ wp_sha1sum }}" 

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp
    owner: root
    group: root
    copy: no

- name: Move WordPress install files
  command: mv /tmp/wordpress /usr/share/nginx/html/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: Add wp-config
  template: "src=wp-config.php dest=/usr/share/nginx/html/wp-config.php"

- name: Update WordPress config file
  lineinfile:
    dest: "/usr/share/nginx/html/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db_name}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_db_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_db_password}}');"}
