# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.define :logsrv do |conf|
    conf.vm.hostname = "logsrv.local"
    conf.vm.network :private_network, ip: "10.0.0.100"
    conf.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "1024" ]
    end
  end

  config.vm.define :web1 do |conf|
    conf.vm.hostname = "web1.local"
    conf.vm.network :private_network, ip: "10.0.0.81"
    conf.vm.provider :virtualbox do |v|
       v.customize ["modifyvm", :id, "--memory", "1024" ]
    end
  end

  config.vm.define :web2 do |conf|
    conf.vm.hostname = "web2.local"
    conf.vm.network :private_network, ip: "10.0.0.82"
    conf.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "1024" ]
  end
end

  config.vm.define :mariadb1 do |conf|
    conf.vm.hostname = "mariadb1.local"
    conf.vm.network :private_network, ip: "10.0.0.91"
    conf.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "1024" ]
    end
  end

  config.vm.define :mariadb2 do |conf|
    conf.vm.hostname = "mariadb2.local"
    conf.vm.network :private_network, ip: "10.0.0.92"
    conf.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "1024" ]
    end
  end

##############  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "site.yml"
  end

end
