version: "3.7"

services:
    nginx:
      build: ./images/nginx
      ports:
        - 80:80
      volumes:
        - ./www:/usr/share/nginx/html
        - ./logs:/var/log/nginx
      links:
        - php

    php:
      build: ./images/php
      ports:
        - 9000:9000
      volumes:
        - ./www:/usr/share/nginx/html
