#-------------------------------------------------------------------------
#Dockerfile to build Docker Image of NGINX Server for OTUS
#
#Made by Nasimi Mamed-zade
#-------------------------------------------------------------------------

FROM nginx:alpine

COPY ./files /usr/share/nginx/html