#-------------------------------------------------------------------------
#Dockerfile to build Docker Image of NGINX Server for OTUS
#
#Made by Nasimi Mamed-zade
#-------------------------------------------------------------------------

FROM php:7.1-fpm

WORKDIR /usr/share/nginx/html

CMD ["php-fpm"]